version: '3.8'

services:

  web:
    build: ./docker/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker/app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app_django
      - POSTGRES_PASSWORD=app_django
      - POSTGRES_DB=app_django_dev

volumes:
  postgres_data: